### Core
set -g default-terminal "xterm-256color"
set -as terminal-overrides ",*:RGB"
set -as terminal-overrides ",*:sitm=\E[3m"
set -as terminal-overrides ",*:ritm=\E[23m"
set -as terminal-overrides ",*:Smulx=\E[4::%p1%dm"
set -as terminal-overrides ",*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m"

set -g status-position top
set -g status-interval 5
set -g history-limit 10000
set -g escape-time 10
setw -g mode-keys vi

### Prefix: Alt+a
unbind C-b
set -g prefix M-a
bind-key M-a send-prefix

### TPM + plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'rose-pine/tmux'

run '~/.tmux/plugins/tpm/tpm'
