-- SynVim default colorscheme
return {
  "rose-pine/neovim",
  name = "rose-pine",
  lazy = false,
  priority = 1000,

  opts = {
    variant = "main",
    dark_variant = "main",
    styles = {
      italic = true,
      bold = true,
      transparency = true,
    },
    groups = {
      border = "muted",
      link = "iris",
      panel = "surface",

      error = "love",
      hint = "iris",
      info = "foam",
      note = "pine",
      todo = "rose",
      warn = "gold",

      git_add = "foam",
      git_change = "rose",
      git_delete = "love",
      git_dirty = "rose",
      git_ignore = "muted",
      git_merge = "iris",
      git_rename = "pine",
      git_stage = "iris",
      git_text = "rose",
      git_untracked = "subtle",

      h1 = "iris",
      h2 = "foam",
      h3 = "rose",
      h4 = "gold",
      h5 = "pine",
      h6 = "foam",
    },
    highlight_groups = {
      TelescopeBorder = { fg = "highlight_high", bg = "none" },
      TelescopeNormal = { bg = "none" },
      TelescopeResultsNormal = { fg = "subtle", bg = "none" },
      TelescopePreviewBorder = { fg = "rose" },
      TelescopePromptBorder = { fg = "iris" },
      TelescopeSelectionCaret = { bg = "rose", fg = "rose" },
      NoicePopupmenu = { bg = "base" },
      NoicePopupmenuBorder = { bg = "base" },
      NoiceCmdlinePopup = { bg = "base" },
      NoiceCmdlinePopupBorder = { bg = "base" },
      BlinkCmpMenu = { fg = "text", bg = "none" },
      BlinkCmpMenuSelection = { bg = "none", fg = "rose", bold = true },
      BlinkCmpMenuBorder = { fg = "pine", bg = "none" },
      BlinkCmpLabelMatch = { bold = true, fg = "text" },
      BlinkCmpLabel = { fg = "subtle" },
      BlinkCmpKind = { fg = "love" },
      BlinkCmpDoc = { bg = "base" },
      BlinkCmpDocBorder = { bg = "base" },
      BlinkCmpDocSeparator = { bg = "base" },
      Visual = { bg = 'surface', inherit = true, italic = true },
      FloatBorder = { fg = "pine" },
      BlinkCmpSignatureHelpActiveParameter = { bg = "base", },
      BlinkCmpGhostText = { fg = "subtle" },
      ColorColumn = { bg = "none" },
      WinSeparator = { fg = "gold" },
      StatColSep = { fg = "muted" },
      IncSearch = { fg = "leaf", bg = "none", bold = true },
      Subsitute = { fg = "rose", bold = true },
      LineNr = { fg = "subtle" },
      CursorLineNr = { fg = "rose", bold = true },
      Whitespace = { fg = "iris" },
      WinBar = { bg = "none" },
      CursorLine = { bg = "none" },
      CurSearch = { fg = "leaf", bg = "leaf", inherit = true },
      Search = { fg = "leaf", bg = "leaf", blend = 20, inherit = true },
      MiniFilesBorder = { fg = "subtle" },
      MiniFilesBorderModified = { fg = "foam" },
      MiniFilesCursorLine = { fg = "text", bold = true },
      MiniFilesNormal = { fg = "subtle" },
      MiniFilesFile = { fg = "subtle" },
      MiniFilesTitle = { bg = "base", fg = "text", italic = true },
      MiniFilesTitleFocused = { bg = "base", fg = "gold", bold = true, italic = true },
      WhichKeyBorder = { fg = "foam" },
      Folded = { fg = "muted", italic = true },
      FoldColumn = { fg = "gold" },
      DropBarHover = { bg = "none", fg = "none", bold = true },
      DashboardHeader = { fg = "rose", bold = true },
      DashboardFooter = { fg = "iris" },
      DashboardIcon = { fg = "gold", bold = true },
      DashboardKey = { fg = "foam", italic = true },
      HLYank = { fg = "love", italic = true, bold = true },
      MiniWindow = { bg = 'surface', fg = 'iris', bold = true },
      StatusLineTerm = { bg = 'none' },
      StatusLineTermNC = { bg = 'none' },
      DiagnosticLineError = { bg = 'base', bold = true },
      DiagnosticVirtualTextError = { bg = 'surface', fg = 'love', italic = true, bold = true },
      DiagnosticVirtualTextWarn = { bg = 'surface', fg = 'gold', italic = true },
      DiagnosticVirtualTextHint = { bg = 'surface', fg = 'iris', italic = true },
      DiagnosticVirtualTextInfo = { bg = 'surface', fg = 'foam', italic = true },
      DiagnosticSignError = { fg = 'love', italic = true, bold = true },
      DiagnosticSignWarn = { fg = 'gold', italic = true },
      DiagnosticSignHint = { fg = 'iris', italic = true },
      DiagnosticSignInfo = { fg = 'foam', italic = true },
    }
  },

  config = function(_, opts)
    require("rose-pine").setup(opts)
    vim.cmd("colorscheme rose-pine-main")
  end,
}
