-- SynVim default colorscheme
return {
	"rose-pine/neovim",
	name = "rose-pine",
	lazy = true,
	-- priority = 1000,

	config = function()
		require("rose-pine").setup({
			variant = "main",
			dark_variant = "main",
			enable = {
				terminal = false,
			},
			styles = {
				italic = true,
				bold = true,
				transparency = true,
			},
			groups = {
				border = "muted",
				link = "iris",
				panel = "surface",

				error = "love",
				hint = "iris",
				info = "foam",
				note = "pine",
				todo = "rose",
				warn = "gold",

				h1 = "iris",
				h2 = "foam",
				h3 = "rose",
				h4 = "gold",
				h5 = "pine",
				h6 = "foam",
			},
			highlight_groups = {
				SnacksPickerListCursorLine = { bg = "none", bold = true, italic = true },
				SnacksPickerPreviewCursorLine = { bg = "none", bold = true, italic = true },
				SnacksPickerPreviewBorder = { fg = "rose" },
				SnacksPickerInputBorder = { fg = "iris" },
				SnacksPickerListBorder = { fg = "subtle", bg = "none" },
				SnacksPickerBoxBorder = { fg = "highlight_high" },
				SnacksPickerDir = { fg = "subtle", italic = true },
				SnacksDashboardIcon = { fg = "iris" },
				NoicePopupmenu = { bg = "base" },
				NoicePopupmenuBorder = { bg = "base" },
				NoiceCmdlinePopup = { bg = "base" },
				NoiceCmdlinePopupBorder = { bg = "base" },
				BlinkCmpMenu = { fg = "text", bg = "none" },
				BlinkCmpMenuSelection = { bg = "pine", fg = "text", bold = true },
				BlinkCmpMenuBorder = { fg = "pine", bg = "none" },
				BlinkCmpLabelMatch = { bold = true, fg = "text" },
				BlinkCmpLabel = { fg = "subtle" },
				BlinkCmpKind = { fg = "love" },
				BlinkCmpDoc = { bg = "base" },
				BlinkCmpDocBorder = { bg = "base" },
				BlinkCmpDocSeparator = { bg = "base" },
				Visual = { bg = "highlight_high", inherit = true, italic = true },
				FloatBorder = { fg = "pine" },
				BlinkCmpSignatureHelpActiveParameter = { bg = "base" },
				BlinkCmpGhostText = { fg = "subtle" },
				ColorColumn = { bg = "none" },
				WinSeparator = { fg = "gold" },
				StatColSep = { fg = "muted" },
				IncSearch = { fg = "leaf", bg = "none", bold = true },
				Subsitute = { fg = "rose", bold = true },
				LineNr = { fg = "subtle" },
				CursorLineNr = { fg = "rose", bold = true },
				Whitespace = { fg = "iris" },
				WinBar = { bg = "none" },
				CursorLine = { bg = "none" },
				CurSearch = { fg = "leaf", bg = "none", inherit = true },
				Search = { fg = "leaf", bg = "none", blend = 20, inherit = true },
				MiniFilesBorder = { fg = "subtle" },
				MiniFilesBorderModified = { fg = "foam" },
				MiniFilesCursorLine = { fg = "text", bold = true },
				MiniFilesNormal = { fg = "subtle" },
				MiniFilesFile = { fg = "subtle" },
				MiniFilesTitle = { bg = "base", fg = "text", italic = true },
				MiniFilesTitleFocused = { bg = "base", fg = "gold", bold = true, italic = true },
				WhichKeyBorder = { fg = "foam" },
				Folded = { fg = "muted", italic = true },
				FoldColumn = { fg = "gold" },
				DropBarHover = { bg = "none", fg = "none", bold = true },
				HLYank = { bg = "love", fg = "surface", italic = true, bold = true },
				MiniWindow = { bg = "surface", fg = "iris", bold = true },
				StatusLineTerm = { bg = "none" },
				StatusLineTermNC = { bg = "none" },
				DiagnosticLineError = { bg = "base", bold = true },
				DiagnosticVirtualTextError = { bg = "surface", fg = "love", italic = true, bold = true },
				DiagnosticVirtualTextWarn = { bg = "surface", fg = "gold", italic = true },
				DiagnosticVirtualTextHint = { bg = "surface", fg = "iris", italic = true },
				DiagnosticVirtualTextInfo = { bg = "surface", fg = "foam", italic = true },
				DiagnosticSignError = { fg = "love", italic = true, bold = true },
				DiagnosticSignWarn = { fg = "gold", italic = true },
				DiagnosticSignHint = { fg = "iris", italic = true },
				DiagnosticSignInfo = { fg = "foam", italic = true },
				Boolean = { bold = true },
				Function = { bold = true, italic = true },
				NoiceLspProgressSpinner = { bg = "none", fg = "rose" },
				NoiceLspProgressTitle = { bg = "none", fg = "iris" },
				TablineAct = { bg = "none", fg = "iris", bold = true, italic = true },
				TablineNC = { bg = "none", fg = "subtle" },
				RenderMarkdownCode = { bg = "none" },
			},
		})

		-- vim.cmd("colorscheme rose-pine-main")
	end,
}
